pipeline:
  identifier: Build_docker_sample_nginx_1683290881562
  name: Build docker-sample-nginx
  orgIdentifier: default
  projectIdentifier: samplecitest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: groots-software-technologies/docker-sample-nginx
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: mydockerhubsecret
                    repo: mayurmadan/samplejs
                    tags:
                      - <+pipeline.sequenceId>
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
  notificationRules:
    - name: sample-ci-test
      identifier: samplecitest
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: PipelinePaused
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - mayur@groots.in
      enabled: true
  tags: {}
