pipeline:
  identifier: Build_docker_sample_nginx_1683290881562
  name: Build docker-sample-nginx
  orgIdentifier: default
  projectIdentifier: samplecitest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: groots-software-technologies/docker-sample-nginx
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: dockerbuild
                      name: docker_build
                      spec:
                        image: plugins/docker
                        settings:
                          dry_run: "true"
                          repo: hello/world
                          tags: latest
                      timeout: ""
                      type: Plugin
                  - step:
                      type: BuildAndPushECR
                      name: BuildAndPushECR_1
                      identifier: BuildAndPushECR_1
                      spec:
                        connectorRef: awsconnector
                        region: ap-south-1
                        account: "983392546126"
                        imageName: harness
                        tags:
                          - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sampleservice
          environment:
            environmentRef: sampleservice
            deployToAll: false
            infrastructureDefinitions:
              - identifier: sampleservice
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: K8sBlueGreenDeploy_1
                  identifier: K8sBlueGreenDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
            rollbackSteps: []
        tags: {}
        delegateSelectors:
          - kubernetes-delegate
        when:
          pipelineStatus: All
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  notificationRules:
    - name: sample-ci-test
      identifier: samplecitest
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: PipelinePaused
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - mayur@groots.in
      enabled: true
  tags: {}
